#!/usr/bin/env python
Import("env")
Import("env_goost")

env_goost.add_source_files(env.modules_sources, "*.cpp")
env_goost.add_source_files(env.modules_sources, "mixin_script/*.cpp")

if env["tools"]:
    env_goost.add_source_files(env.modules_sources, "mixin_script/editor/*.cpp")
