#!/usr/bin/env python
Import("env")
Import("env_goost")

if env["tools"] and env["goost_editor_enabled"]:
    SConscript("editor/SCsub", exports="env_goost")

env_goost.add_source_files(env.modules_sources, "*.cpp")
