short_name = "goost"
name = "Goost: Godot Engine Extension"
url = "https://github.com/goostengine/goost"
website = "https://goostengine.github.io/"
major = 1
minor = 0
patch = 0
status = "stable"
year = 2021
