#!/usr/bin/env python

import os
from core import components

Import("env")
env_goost = env.Clone()

# Make include paths independent of Goost location.
env_goost.Prepend(CPPPATH=[os.path.dirname(os.path.realpath(os.curdir))])

# Add options to build core components.
for name in components:
    opt = "goost_%s_enabled" % (name)
    if env_goost[opt]:
        env_goost.Prepend(CPPDEFINES=[opt.upper()])

env_goost.Prepend(CPPDEFINES={"SCALE_FACTOR" : env_goost["goost_scale_factor"]})

# Build subdirs, the build order is dependent on the link order.
subdirs = [
    "core",
    "scene",
    "editor",
    "thirdparty",
    # "modules", # Cannot build directly, use `custom_modules` option explicitly.
]
SConscript(dirs=subdirs, name="SCsub", exports="env_goost")

env_goost.add_source_files(env.modules_sources, "*.cpp")
