#!/usr/bin/env python
Import("env")
Import("env_goost")

env_goost.add_source_files(env_goost.modules_sources, "2d/*.cpp")

if not env["disable_3d"]:
    env_goost.add_source_files(env_goost.modules_sources, "3d/*.cpp")
