#!/bin/sh
#
# This hook allows to run tests automatically before committing changes locally.
# Use "wip", "[wip]", "[ci skip]" or "[skip ci]" keywords in the commit message
# descriptions to skip running tests.
#
if grep -iq -e 'wip' -e '\[wip\]' -e '\[ci skip\]' -e '\[skip ci\]' "$1"; then
  echo "Skipping tests."
else
  python run.py --windowed tests
fi
