#!/usr/bin/env python
Import("env_goost")

if env_goost["goost_image_enabled"]:
    SConscript("image/SCsub", exports="env_goost")

if env_goost["goost_math_enabled"]:
    SConscript("math/SCsub", exports="env_goost")

env_goost.add_source_files(env_goost.modules_sources, "*.cpp")
