#!/usr/bin/env python

Import('env')
Import('env_modules')

env_gif = env_modules.Clone()

thirdparty_dir = "./thirdparty/giflib/"
thirdparty_sources = [
    "gif_err.c",
    "dgif_lib.c",
    "egif_lib.c",
    "gifalloc.c",
    "gif_hash.c",
    "openbsd-reallocarray.c"
]
thirdparty_sources = [thirdparty_dir + file for file in thirdparty_sources]

env_gif.Prepend(CPPPATH=[thirdparty_dir])
env_gif.Prepend(CPPPATH=["./"])

env_thirdparty = env_gif.Clone()
env_thirdparty.disable_warnings()
env_thirdparty.add_source_files(env.modules_sources, thirdparty_sources)

env_gif.add_source_files(env.modules_sources, "*.cpp")
env_gif.add_source_files(env.modules_sources, "editor/import/*.cpp")
