#!/usr/bin/env python
Import("env")
Import("env_goost")

subdirs = [
    "geometry",
]
SConscript(dirs=subdirs, name="SCsub", exports="env_goost")

env_goost.add_source_files(env.modules_sources, "*.cpp")
