#!/usr/bin/env python3

Import("env")
Import("env_goost")

if env["goost_geometry_enabled"]:
    SConscript("geometry/SCsub", exports="env_goost")

env_goost.add_source_files(env.modules_sources, "*.cpp")
