#!/usr/bin/env python
Import("env")
Import("env_goost")

SConscript("2d/SCsub", exports="env_goost")

if not env["disable_3d"]:
    env_goost.add_source_files(env.modules_sources, "3d/*.cpp")
    SConscript("3d/SCsub", exports="env_goost")

env_goost.add_source_files(env.modules_sources, "*.cpp")
