#!/usr/bin/env python
Import("env")
Import("env_goost")

SConscript("2d/SCsub", exports="env_goost")

if not env["disable_3d"]:
    SConscript("3d/SCsub", exports="env_goost")

env_goost.add_source_files(env_goost.modules_sources, "*.cpp")
